name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Install juliaup
      uses: julia-actions/install-juliaup@v2.1.2
      with:
        channel: '1'
    - name: Update Julia registry 
      shell: julia --project=. --color=yes {0}
      run: |
        using Pkg
        Pkg.Registry.update()
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -e .[test] # to put juliapkg.json in sys.path
        python -c 'import juliacall' # force install of all deps
    - name: Benchmark
      run: |
        pytest -n 0 benchmark/benchmark.py --benchmark-json=benchmark/output.json
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Python Benchmark with pytest-benchmark
        tool: 'pytest'
        output-file-path: benchmark/output.json
        # don't auto-deploy to gh-pages for now
        #github-token: ${{ secrets.GITHUB_TOKEN }}
        #auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        # comment-on-alert: true
        fail-on-alert: true
